// Simple template for C++ -> Rust shim that forwards calls to the Rust
// `binaryen-ffi` crate.  Copy or adapt this into your own component and
// replace `MyThing` / `MyThingDo` with your function names.

#pragma once

#ifdef BUILD_RUST_COMPONENTS
#include "../../include/binaryen_ffi.h"
#include <cstddef>

extern "C" {
  // Example: In Rust, export
  // #[no_mangle]
  // pub extern "C" fn BinaryenMyThingDo(ptr: *mut MyThing, x: u32) -> u32 { ... }
  
  // C prototype generated by cbindgen should be visible: align with names
  unsigned int BinaryenMyThingDo(void* t, unsigned int x);
}

// C++ wrappers
inline unsigned int MyThingDo(void* t, unsigned int x) {
  return BinaryenMyThingDo(t, x);
}

#else

// Fallback C++ implementation used when rust components are disabled. Provide
// a C++ implementation here that keeps the public interface stable.
inline unsigned int MyThingDo(void* t, unsigned int x) {
  // C++ fallback implementation
  return 0;
}

#endif // BUILD_RUST_COMPONENTS
